server {
    listen 80;
    server_name localhost;

    # Thư mục chứa mã nguồn website
    root /var/www/my-web/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    # 1. Cấu hình trang báo lỗi 404 tùy chỉnh
    error_page 404 /404.html;

    # 2. Thiết lập chặn người dùng bên ngoài truy cập trực tiếp tệp tin này
    location = /404.html {
        root /var/www/my-web/html;
        internal;
    }
}